development:
  adapter: redis
  url: redis://localhost:6479/1
  channel_prefix: test-task-development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6479/2
  channel_prefix: test-task-production
